# Generated by Django 5.2.8 on 2025-12-14 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lessons", "0002_alter_opcionmultiple_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgresoTema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("NO_INICIADO", "No Iniciado"),
                            ("EN_PROGRESO", "En Progreso"),
                            ("COMPLETADO", "Completado"),
                        ],
                        default="NO_INICIADO",
                        max_length=20,
                    ),
                ),
                ("desbloqueado", models.BooleanField(default=False)),
                ("fecha_inicio", models.DateTimeField(blank=True, null=True)),
                ("fecha_completado", models.DateTimeField(blank=True, null=True)),
                ("intentos_realizados", models.PositiveIntegerField(default=0)),
                ("porcentaje_acierto", models.FloatField(default=0.0)),
                (
                    "tiempo_total_teoria_segundos",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Tiempo total acumulado viendo pantallas de TEORÍA",
                    ),
                ),
                (
                    "tiempo_total_ejemplos_segundos",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Tiempo total acumulado viendo pantallas de EJEMPLO (no incluye EJEMPLO_EXTRA)",
                    ),
                ),
                (
                    "tiempo_total_ejemplos_extra_segundos",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Tiempo total acumulado viendo pantallas de EJEMPLO_EXTRA",
                    ),
                ),
                (
                    "clics_ver_otro_ejemplo",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Cantidad de veces que hizo clic en 'Ver Otro Ejemplo'",
                    ),
                ),
                (
                    "clics_volver_contenido",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Cantidad de veces que hizo clic en '← Volver' desde contenido (teoría/ejemplos)",
                    ),
                ),
                (
                    "clics_volver_ejercicios",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Cantidad de veces que hizo clic en '← Volver al Tema' desde ejercicios",
                    ),
                ),
                (
                    "clics_ir_a_ejercicios",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Cantidad de veces que hizo clic en 'Ir a Ejercicios →'",
                    ),
                ),
                (
                    "clics_ayuda_total",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Cantidad total de veces que solicitó ayuda en ejercicios del tema",
                    ),
                ),
                (
                    "contenido_completado",
                    models.ManyToManyField(
                        blank=True,
                        related_name="completado_por",
                        to="lessons.contenidotema",
                    ),
                ),
                (
                    "tema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progresos",
                        to="lessons.tema",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progresos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Progreso de Tema",
                "verbose_name_plural": "Progresos de Temas",
                "ordering": ["tema__orden"],
                "unique_together": {("usuario", "tema")},
            },
        ),
        migrations.CreateModel(
            name="RespuestaEjercicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("respuesta_usuario", models.TextField()),
                ("es_correcta", models.BooleanField()),
                ("uso_ayuda", models.BooleanField(default=False)),
                (
                    "tiempo_respuesta_segundos",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Tiempo que tardó en responder este ejercicio específico",
                    ),
                ),
                ("fecha_respuesta", models.DateTimeField(auto_now_add=True)),
                (
                    "ejercicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respuestas",
                        to="lessons.ejercicio",
                    ),
                ),
                (
                    "progreso_tema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respuestas",
                        to="tracking.progresotema",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respuestas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Respuesta de Ejercicio",
                "verbose_name_plural": "Respuestas de Ejercicios",
                "ordering": ["-fecha_respuesta"],
            },
        ),
        migrations.CreateModel(
            name="SesionEstudio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateTimeField(auto_now_add=True)),
                ("fecha_fin", models.DateTimeField(blank=True, null=True)),
                (
                    "duracion_segundos",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sesiones_estudio",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sesión de Estudio",
                "verbose_name_plural": "Sesiones de Estudio",
                "ordering": ["-fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="ActividadPantalla",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_pantalla",
                    models.CharField(
                        choices=[
                            ("LOGIN", "Login"),
                            ("REGISTRO", "Registro"),
                            ("LISTA_LECCIONES", "Lista de Lecciones"),
                            ("DETALLE_LECCION", "Detalle de Lección"),
                            ("CONTENIDO_TEMA", "Contenido del Tema"),
                            ("EJERCICIOS", "Ejercicios"),
                        ],
                        max_length=50,
                    ),
                ),
                ("fecha_inicio", models.DateTimeField(auto_now_add=True)),
                ("fecha_fin", models.DateTimeField(blank=True, null=True)),
                (
                    "duracion_segundos",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "ejercicio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actividades",
                        to="lessons.ejercicio",
                    ),
                ),
                (
                    "leccion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actividades",
                        to="lessons.leccion",
                    ),
                ),
                (
                    "tema",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actividades",
                        to="lessons.tema",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actividades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sesion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actividades",
                        to="tracking.sesionestudio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Actividad de Pantalla",
                "verbose_name_plural": "Actividades de Pantalla",
                "ordering": ["-fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="ProgresoLeccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateTimeField(auto_now_add=True)),
                ("fecha_ultimo_acceso", models.DateTimeField(auto_now=True)),
                (
                    "leccion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progresos",
                        to="lessons.leccion",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progresos_leccion",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Progreso de Lección",
                "verbose_name_plural": "Progresos de Lecciones",
                "ordering": ["leccion__orden"],
                "unique_together": {("usuario", "leccion")},
            },
        ),
    ]
