# Generated by Django 5.2.8 on 2025-12-15 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0002_alter_opcionmultiple_options_and_more"),
        ("tracking", "0002_tracking_detallado_final"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="actividadpantalla",
            options={
                "ordering": ["-tiempo_inicio"],
                "verbose_name": "Actividad de Pantalla",
                "verbose_name_plural": "Actividades de Pantalla",
            },
        ),
        migrations.AlterModelOptions(
            name="progresoleccion",
            options={
                "ordering": ["leccion__orden"],
                "verbose_name": "Progreso de Lección",
                "verbose_name_plural": "Progreso de Lecciones",
            },
        ),
        migrations.AlterModelOptions(
            name="progresotema",
            options={
                "ordering": ["tema__orden"],
                "verbose_name": "Progreso de Tema",
                "verbose_name_plural": "Progreso de Temas",
            },
        ),
        migrations.RenameField(
            model_name="actividadpantalla",
            old_name="fecha_fin",
            new_name="tiempo_fin",
        ),
        migrations.RenameField(
            model_name="actividadpantalla",
            old_name="fecha_inicio",
            new_name="tiempo_inicio",
        ),
        migrations.RemoveField(
            model_name="actividadpantalla",
            name="duracion_segundos",
        ),
        migrations.RemoveField(
            model_name="actividadpantalla",
            name="ejercicio",
        ),
        migrations.RemoveField(
            model_name="actividadpantalla",
            name="leccion",
        ),
        migrations.RemoveField(
            model_name="actividadpantalla",
            name="sesion",
        ),
        migrations.RemoveField(
            model_name="actividadpantalla",
            name="tema",
        ),
        migrations.RemoveField(
            model_name="progresoleccion",
            name="fecha_ultimo_acceso",
        ),
        migrations.RemoveField(
            model_name="progresotema",
            name="clics_ayuda_total",
        ),
        migrations.RemoveField(
            model_name="progresotema",
            name="clics_ir_a_ejercicios",
        ),
        migrations.RemoveField(
            model_name="progresotema",
            name="clics_ver_otro_ejemplo",
        ),
        migrations.RemoveField(
            model_name="progresotema",
            name="clics_volver_contenido",
        ),
        migrations.RemoveField(
            model_name="progresotema",
            name="clics_volver_ejercicios",
        ),
        migrations.RemoveField(
            model_name="progresotema",
            name="contenido_completado",
        ),
        migrations.RemoveField(
            model_name="progresotema",
            name="tiempo_total_ejemplos_extra_segundos",
        ),
        migrations.RemoveField(
            model_name="progresotema",
            name="tiempo_total_ejemplos_segundos",
        ),
        migrations.RemoveField(
            model_name="progresotema",
            name="tiempo_total_teoria_segundos",
        ),
        migrations.RemoveField(
            model_name="sesionestudio",
            name="duracion_segundos",
        ),
        migrations.AddField(
            model_name="actividadpantalla",
            name="leccion_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="actividadpantalla",
            name="tema_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="actividadpantalla",
            name="tiempo_segundos",
            field=models.IntegerField(
                default=0, help_text="Tiempo total en la pantalla en segundos"
            ),
        ),
        migrations.AddField(
            model_name="actividadpantalla",
            name="veces_ir_a_ejercicios",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Número de veces que fue directo a ejercicios desde el contenido",
            ),
        ),
        migrations.AddField(
            model_name="actividadpantalla",
            name="veces_ver_ejemplo_extra",
            field=models.PositiveIntegerField(
                default=0, help_text="Número de veces que presionó 'Ver Otro Ejemplo'"
            ),
        ),
        migrations.AddField(
            model_name="actividadpantalla",
            name="veces_volver_contenido",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Número de veces que presionó el botón 'Volver' en el contenido del tema",
            ),
        ),
        migrations.AddField(
            model_name="progresoleccion",
            name="estado",
            field=models.CharField(
                choices=[
                    ("SIN_INICIAR", "Sin Iniciar"),
                    ("EN_PROGRESO", "En Progreso"),
                    ("COMPLETADA", "Completada"),
                ],
                default="SIN_INICIAR",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="progresoleccion",
            name="fecha_completado",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="progresoleccion",
            name="porcentaje_completado",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Porcentaje de temas completados en la lección",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="progresotema",
            name="contenidos_vistos",
            field=models.ManyToManyField(
                blank=True,
                help_text="Contenidos que el usuario ha visto (excluyendo EJEMPLO_EXTRA)",
                related_name="visto_por",
                to="lessons.contenidotema",
            ),
        ),
        migrations.AddField(
            model_name="sesionestudio",
            name="duracion_minutos",
            field=models.IntegerField(
                default=0, help_text="Duración total de la sesión en minutos"
            ),
        ),
        migrations.AlterField(
            model_name="actividadpantalla",
            name="tipo_pantalla",
            field=models.CharField(
                choices=[
                    ("LOGIN", "Login"),
                    ("REGISTRO", "Registro"),
                    ("LISTA_LECCIONES", "Lista de Lecciones"),
                    ("DETALLE_LECCION", "Detalle de Lección"),
                    ("CONTENIDO_TEMA", "Contenido del Tema"),
                    ("EJERCICIOS", "Ejercicios"),
                    ("OTRA", "Otra"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="actividadpantalla",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actividades_pantalla",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="progresoleccion",
            name="fecha_inicio",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="progresoleccion",
            name="leccion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progreso_usuarios",
                to="lessons.leccion",
            ),
        ),
        migrations.AlterField(
            model_name="progresoleccion",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progreso_lecciones",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="progresotema",
            name="desbloqueado",
            field=models.BooleanField(
                default=False,
                help_text="Indica si el tema está desbloqueado para el usuario",
            ),
        ),
        migrations.AlterField(
            model_name="progresotema",
            name="estado",
            field=models.CharField(
                choices=[
                    ("SIN_INICIAR", "Sin Iniciar"),
                    ("INICIADO", "Iniciado"),
                    ("COMPLETADO", "Completado"),
                ],
                default="SIN_INICIAR",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="progresotema",
            name="intentos_realizados",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Número de veces que el usuario ha intentado completar este tema",
            ),
        ),
        migrations.AlterField(
            model_name="progresotema",
            name="porcentaje_acierto",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Porcentaje de aciertos en los ejercicios del tema",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="progresotema",
            name="tema",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progreso_usuarios",
                to="lessons.tema",
            ),
        ),
        migrations.AlterField(
            model_name="progresotema",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progreso_temas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="respuestaejercicio",
            name="ejercicio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="respuestas_usuarios",
                to="lessons.ejercicio",
            ),
        ),
        migrations.AlterField(
            model_name="respuestaejercicio",
            name="es_correcta",
            field=models.BooleanField(help_text="Indica si la respuesta fue correcta"),
        ),
        migrations.AlterField(
            model_name="respuestaejercicio",
            name="progreso_tema",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="respuestas",
                to="tracking.progresotema",
            ),
        ),
        migrations.AlterField(
            model_name="respuestaejercicio",
            name="respuesta_usuario",
            field=models.TextField(help_text="Respuesta proporcionada por el usuario"),
        ),
        migrations.AlterField(
            model_name="respuestaejercicio",
            name="tiempo_respuesta_segundos",
            field=models.IntegerField(
                default=0,
                help_text="Tiempo que tardó el usuario en responder (en segundos)",
            ),
        ),
        migrations.AlterField(
            model_name="respuestaejercicio",
            name="uso_ayuda",
            field=models.BooleanField(
                default=False,
                help_text="Indica si el usuario vio la ayuda antes de responder",
            ),
        ),
        migrations.AlterField(
            model_name="sesionestudio",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sesiones",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="IntentoTema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_intento",
                    models.PositiveIntegerField(
                        help_text="Número de intento (1, 2, 3, ...)"
                    ),
                ),
                (
                    "ejercicios_correctos",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Cantidad de ejercicios respondidos correctamente",
                    ),
                ),
                (
                    "ejercicios_incorrectos",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Cantidad de ejercicios respondidos incorrectamente",
                    ),
                ),
                (
                    "ejercicios_totales",
                    models.PositiveIntegerField(
                        help_text="Total de ejercicios del tema"
                    ),
                ),
                (
                    "porcentaje_acierto",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Porcentaje de aciertos en este intento",
                        max_digits=5,
                    ),
                ),
                (
                    "ejercicios_con_ayuda",
                    models.PositiveIntegerField(
                        default=0, help_text="Cantidad de ejercicios donde usó la ayuda"
                    ),
                ),
                (
                    "tiempo_total_segundos",
                    models.IntegerField(
                        default=0, help_text="Tiempo total invertido en este intento"
                    ),
                ),
                (
                    "tiempo_promedio_por_ejercicio",
                    models.IntegerField(
                        default=0, help_text="Tiempo promedio por ejercicio en segundos"
                    ),
                ),
                (
                    "aprobado",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si alcanzó el 80% requerido para aprobar",
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateTimeField(
                        help_text="Fecha y hora en que comenzó el intento"
                    ),
                ),
                (
                    "fecha_finalizacion",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Fecha y hora en que finalizó el intento",
                    ),
                ),
                (
                    "mejora_porcentaje",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Mejora en porcentaje respecto al intento anterior",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "progreso_tema",
                    models.ForeignKey(
                        help_text="Relación con el progreso general del tema",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intentos",
                        to="tracking.progresotema",
                    ),
                ),
                (
                    "tema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intentos",
                        to="lessons.tema",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intentos_temas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Intento de Tema",
                "verbose_name_plural": "Intentos de Temas",
                "ordering": ["-fecha_finalizacion"],
                "unique_together": {("usuario", "tema", "numero_intento")},
            },
        ),
    ]
