# Generated by Django 5.2.8 on 2025-12-15 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0002_alter_opcionmultiple_options_and_more"),
        ("tracking", "0003_alter_actividadpantalla_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="progresotema",
            name="clics_ayuda",
            field=models.PositiveIntegerField(
                default=0, help_text="Cantidad de veces que hizo clic en 'Ver Ayuda'"
            ),
        ),
        migrations.AddField(
            model_name="progresotema",
            name="clics_ir_ejercicios",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Cantidad de veces que hizo clic en 'Ir a ejercicios'",
            ),
        ),
        migrations.AddField(
            model_name="progresotema",
            name="clics_regresar",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Cantidad de veces que hizo clic en 'Regresar' en el contenido",
            ),
        ),
        migrations.AddField(
            model_name="progresotema",
            name="clics_ver_otro_ejemplo",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Cantidad de veces que hizo clic en 'Ver otro ejemplo'",
            ),
        ),
        migrations.AddField(
            model_name="progresotema",
            name="clics_volver_tema",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Cantidad de veces que hizo clic en 'Volver al tema' desde ejercicios",
            ),
        ),
        migrations.AddField(
            model_name="progresotema",
            name="tiempo_total_ejemplos_segundos",
            field=models.IntegerField(
                default=0,
                help_text="Tiempo total en segundos viendo contenido de ejemplos",
            ),
        ),
        migrations.AddField(
            model_name="progresotema",
            name="tiempo_total_teoria_segundos",
            field=models.IntegerField(
                default=0,
                help_text="Tiempo total en segundos viendo contenido de teoría",
            ),
        ),
        migrations.CreateModel(
            name="EventoTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_evento",
                    models.CharField(
                        choices=[
                            ("TEORIA_VISTA", "Teoría Vista"),
                            ("EJEMPLO_VISTO", "Ejemplo Visto"),
                            ("EJERCICIO_VISTO", "Ejercicio Visto"),
                            ("CLIC_VER_OTRO_EJEMPLO", "Clic Ver Otro Ejemplo"),
                            ("CLIC_REGRESAR", "Clic Regresar"),
                            ("CLIC_VOLVER_TEMA", "Clic Volver al Tema"),
                            ("CLIC_IR_EJERCICIOS", "Clic Ir a Ejercicios"),
                            ("CLIC_AYUDA", "Clic Ver Ayuda"),
                            ("CAMBIO_PESTANA", "Cambio de Pestaña"),
                        ],
                        help_text="Tipo de evento registrado",
                        max_length=30,
                    ),
                ),
                (
                    "contenido_id",
                    models.IntegerField(
                        blank=True,
                        help_text="ID del ContenidoTema si aplica",
                        null=True,
                    ),
                ),
                (
                    "ejercicio_id",
                    models.IntegerField(
                        blank=True, help_text="ID del Ejercicio si aplica", null=True
                    ),
                ),
                (
                    "numero_intento",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Número de intento para ejercicios",
                        null=True,
                    ),
                ),
                (
                    "tiempo_segundos",
                    models.IntegerField(
                        blank=True,
                        help_text="Tiempo en segundos (null si hubo cambio de pestaña)",
                        null=True,
                    ),
                ),
                (
                    "cambio_pestana",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si el usuario cambió de pestaña durante este evento",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha y hora del evento"
                    ),
                ),
                (
                    "tema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventos_tracking",
                        to="lessons.tema",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventos_tracking",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento de Tracking",
                "verbose_name_plural": "Eventos de Tracking",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["usuario", "tema"],
                        name="tracking_ev_usuario_f69140_idx",
                    ),
                    models.Index(
                        fields=["tipo_evento"], name="tracking_ev_tipo_ev_a4bfb7_idx"
                    ),
                    models.Index(
                        fields=["timestamp"], name="tracking_ev_timesta_30a977_idx"
                    ),
                ],
            },
        ),
    ]
