# Generated by Django 5.2.8 on 2025-12-15 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0002_alter_opcionmultiple_options_and_more"),
        ("tracking", "0004_progresotema_clics_ayuda_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sesionestudio",
            name="duracion_segundos",
            field=models.PositiveIntegerField(
                default=0, help_text="Duración total de la sesión en segundos"
            ),
        ),
        migrations.AddField(
            model_name="sesionestudio",
            name="tipo_cierre",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LOGOUT", "Logout Explícito"),
                    ("INACTIVIDAD", "Inactividad (5 min)"),
                    ("CIERRE_VENTANA", "Cierre de Ventana/Pestaña"),
                ],
                help_text="Tipo de cierre de la sesión",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sesionestudio",
            name="ultima_actividad",
            field=models.DateTimeField(
                blank=True,
                help_text="Última actividad registrada en la sesión",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sesionestudio",
            name="duracion_minutos",
            field=models.IntegerField(
                default=0,
                help_text="Duración total de la sesión en minutos (DEPRECATED, usar duracion_segundos)",
            ),
        ),
        migrations.CreateModel(
            name="ClicBoton",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_boton",
                    models.CharField(
                        choices=[
                            ("REGRESAR", "Regresar"),
                            ("IR_EJERCICIOS", "Ir a ejercicios"),
                            ("VOLVER", "Volver"),
                            ("OTRO_EJEMPLO", "Otro ejemplo"),
                            ("VER_AYUDA", "Ver Ayuda"),
                        ],
                        help_text="Tipo de botón clickeado",
                        max_length=20,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha y hora del clic"
                    ),
                ),
                (
                    "tema",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tema relacionado (null si es navegación global)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clics_botones",
                        to="lessons.tema",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clics_botones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Clic en Botón",
                "verbose_name_plural": "Clics en Botones",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["usuario", "tema"],
                        name="tracking_cl_usuario_09a14e_idx",
                    ),
                    models.Index(
                        fields=["tipo_boton"], name="tracking_cl_tipo_bo_268757_idx"
                    ),
                    models.Index(
                        fields=["timestamp"], name="tracking_cl_timesta_1c6e37_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TiempoPantalla",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_contenido",
                    models.CharField(
                        choices=[
                            ("TEORIA", "Teoría"),
                            ("EJEMPLO", "Ejemplo"),
                            ("EJERCICIO", "Ejercicio"),
                        ],
                        help_text="Tipo de contenido (Teoría, Ejemplo, Ejercicio)",
                        max_length=20,
                    ),
                ),
                (
                    "numero",
                    models.PositiveIntegerField(
                        help_text="Número del contenido dentro del tema (1, 2, 3...)"
                    ),
                ),
                (
                    "tiempo_segundos",
                    models.PositiveIntegerField(
                        help_text="Tiempo en segundos que pasó en esta pantalla"
                    ),
                ),
                (
                    "cambio_pestana",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si el usuario cambió de pestaña durante esta visita",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha y hora del registro"
                    ),
                ),
                (
                    "contenido",
                    models.ForeignKey(
                        blank=True,
                        help_text="Referencia al contenido específico (Teoría o Ejemplo)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tiempos_registrados",
                        to="lessons.contenidotema",
                    ),
                ),
                (
                    "ejercicio",
                    models.ForeignKey(
                        blank=True,
                        help_text="Referencia al ejercicio específico",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tiempos_registrados",
                        to="lessons.ejercicio",
                    ),
                ),
                (
                    "tema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tiempos_pantalla",
                        to="lessons.tema",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tiempos_pantalla",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tiempo en Pantalla",
                "verbose_name_plural": "Tiempos en Pantalla",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["usuario", "tema"],
                        name="tracking_ti_usuario_aeecaf_idx",
                    ),
                    models.Index(
                        fields=["tipo_contenido"], name="tracking_ti_tipo_co_e054c8_idx"
                    ),
                    models.Index(
                        fields=["timestamp"], name="tracking_ti_timesta_29122c_idx"
                    ),
                ],
            },
        ),
    ]
