# Generated by Django 5.2.8 on 2025-12-26 05:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0002_alter_opcionmultiple_options_and_more"),
        ("tracking", "0005_sesionestudio_duracion_segundos_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="actividadpantalla",
            index=models.Index(
                fields=["usuario", "tipo_pantalla"],
                name="tracking_ac_usuario_c25fac_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="actividadpantalla",
            index=models.Index(
                fields=["tiempo_inicio"], name="tracking_ac_tiempo__f436e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="actividadpantalla",
            index=models.Index(
                fields=["leccion_id", "tema_id"], name="tracking_ac_leccion_ffba80_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="intentotema",
            index=models.Index(
                fields=["usuario", "tema", "aprobado"],
                name="tracking_in_usuario_5b8e74_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="intentotema",
            index=models.Index(
                fields=["fecha_finalizacion"], name="tracking_in_fecha_f_3973e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="intentotema",
            index=models.Index(
                fields=["tema", "aprobado"], name="tracking_in_tema_id_36be8e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="respuestaejercicio",
            index=models.Index(
                fields=["usuario", "ejercicio"], name="tracking_re_usuario_33ce72_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="respuestaejercicio",
            index=models.Index(
                fields=["progreso_tema", "es_correcta"],
                name="tracking_re_progres_190b4b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="respuestaejercicio",
            index=models.Index(
                fields=["fecha_respuesta"], name="tracking_re_fecha_r_09a2bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sesionestudio",
            index=models.Index(
                fields=["usuario", "fecha_inicio"],
                name="tracking_se_usuario_88ea7f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sesionestudio",
            index=models.Index(
                fields=["usuario", "tipo_cierre"], name="tracking_se_usuario_56da5b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sesionestudio",
            index=models.Index(
                fields=["fecha_inicio"], name="tracking_se_fecha_i_82ca93_idx"
            ),
        ),
    ]
