# Generated by Django 5.2.8 on 2025-12-03 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="opcionmultiple",
            options={
                "ordering": ["letra"],
                "verbose_name": "Opción Múltiple",
                "verbose_name_plural": "Opciones Múltiples",
            },
        ),
        migrations.AlterField(
            model_name="contenidotema",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("TEORIA", "Teoría"),
                    ("EJEMPLO", "Ejemplo"),
                    ("EJEMPLO_EXTRA", "Ejemplo Extra"),
                    ("RESUMEN", "Resumen"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="opcionmultiple",
            name="ejercicio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="opciones",
                to="lessons.ejercicio",
            ),
        ),
        migrations.AlterField(
            model_name="opcionmultiple",
            name="letra",
            field=models.CharField(
                choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")], max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="opcionmultiple",
            name="texto",
            field=models.TextField(help_text="Texto de la opción"),
        ),
    ]
