# Generated by Django 5.2.8 on 2025-12-28 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0002_alter_opcionmultiple_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ejercicio",
            name="obligatorio",
            field=models.BooleanField(
                default=False,
                help_text="Si está marcado, este ejercicio aparece en el grupo de Control. El grupo Experimental ve ejercicios según su clasificación de autoeficacia.",
                verbose_name="Obligatorio para Control",
            ),
        ),
    ]
