# Generated by Django 5.2.8 on 2025-12-28 00:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lessons", "0003_ejercicio_obligatorio"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CodigoAcceso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Código que los estudiantes ingresarán (LMB o MLZ)",
                        max_length=10,
                        unique=True,
                        verbose_name="Código de Acceso",
                    ),
                ),
                (
                    "grupo",
                    models.CharField(
                        choices=[
                            ("CONTROL", "Control"),
                            ("EXPERIMENTAL", "Experimental"),
                        ],
                        max_length=15,
                        verbose_name="Grupo Asignado",
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True,
                        help_text="Si está inactivo, el código no será válido para nuevos registros",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        help_text="Notas internas sobre este código",
                        verbose_name="Descripción",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Código de Acceso",
                "verbose_name_plural": "Códigos de Acceso",
                "ordering": ["grupo", "codigo"],
            },
        ),
        migrations.CreateModel(
            name="ClasificacionML",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nivel_rendimiento",
                    models.CharField(
                        choices=[
                            ("ALTO", "Alto Rendimiento"),
                            ("MEDIO", "Rendimiento Medio"),
                            ("BAJO", "Bajo Rendimiento"),
                        ],
                        max_length=20,
                        verbose_name="Nivel de Rendimiento Calculado",
                    ),
                ),
                (
                    "confianza",
                    models.FloatField(
                        help_text="Porcentaje de confianza de la clasificación",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                        verbose_name="Confianza del Modelo (%)",
                    ),
                ),
                (
                    "caracteristicas_json",
                    models.JSONField(
                        blank=True,
                        help_text="JSON con las características que se usaron para la clasificación",
                        null=True,
                        verbose_name="Características Utilizadas",
                    ),
                ),
                (
                    "fecha_clasificacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Clasificación"
                    ),
                ),
                (
                    "leccion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clasificaciones_ml",
                        to="lessons.leccion",
                        verbose_name="Lección Evaluada",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clasificaciones_ml",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clasificación ML",
                "verbose_name_plural": "Clasificaciones ML",
                "ordering": ["usuario", "leccion__orden", "-fecha_clasificacion"],
            },
        ),
        migrations.CreateModel(
            name="PerfilUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grupo",
                    models.CharField(
                        choices=[
                            ("CONTROL", "Control"),
                            ("EXPERIMENTAL", "Experimental"),
                        ],
                        max_length=15,
                        verbose_name="Grupo Experimental",
                    ),
                ),
                (
                    "codigo_usado",
                    models.CharField(
                        help_text="Código de acceso que usó para registrarse",
                        max_length=10,
                        verbose_name="Código Utilizado",
                    ),
                ),
                (
                    "clasificacion_autoeficacia",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ALTO", "Alto"),
                            ("MEDIO", "Medio"),
                            ("BAJO", "Bajo"),
                        ],
                        help_text="Clasificación calculada a partir de la escala de autoeficacia pre-test",
                        max_length=20,
                        null=True,
                        verbose_name="Clasificación de Autoeficacia",
                    ),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "completo_autoeficacia_pre",
                    models.BooleanField(
                        default=False, verbose_name="Completó Autoeficacia Pre-test"
                    ),
                ),
                (
                    "completo_diagnostico",
                    models.BooleanField(
                        default=False, verbose_name="Completó Examen Diagnóstico"
                    ),
                ),
                (
                    "completo_autoeficacia_post",
                    models.BooleanField(
                        default=False, verbose_name="Completó Autoeficacia Post-test"
                    ),
                ),
                (
                    "completo_final",
                    models.BooleanField(
                        default=False, verbose_name="Completó Examen Final"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Usuario",
                "verbose_name_plural": "Perfiles de Usuarios",
                "ordering": ["grupo", "user__username"],
            },
        ),
        migrations.CreateModel(
            name="MetricasML",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_ejercicios",
                    models.IntegerField(
                        default=0, verbose_name="Total de Ejercicios Vistos"
                    ),
                ),
                (
                    "ejercicios_correctos_primer_intento",
                    models.IntegerField(
                        default=0, verbose_name="Ejercicios Correctos al Primer Intento"
                    ),
                ),
                (
                    "ejercicios_correctos_varios_intentos",
                    models.IntegerField(
                        default=0,
                        verbose_name="Ejercicios Correctos en Varios Intentos",
                    ),
                ),
                (
                    "ejercicios_con_ayuda",
                    models.IntegerField(
                        default=0, verbose_name="Ejercicios con Ayuda Solicitada"
                    ),
                ),
                (
                    "tiempo_total_segundos",
                    models.IntegerField(
                        default=0, verbose_name="Tiempo Total (segundos)"
                    ),
                ),
                (
                    "tiempo_promedio_por_ejercicio",
                    models.FloatField(
                        default=0.0,
                        verbose_name="Tiempo Promedio por Ejercicio (segundos)",
                    ),
                ),
                (
                    "total_intentos",
                    models.IntegerField(
                        default=0,
                        verbose_name="Total de Intentos en Todos los Ejercicios",
                    ),
                ),
                (
                    "veces_retrocedio",
                    models.IntegerField(
                        default=0,
                        verbose_name="Veces que Retrocedió a Contenido Anterior",
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Inicio de Lección"
                    ),
                ),
                (
                    "fecha_finalizacion",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Fecha de Finalización de Lección",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "leccion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metricas_ml",
                        to="lessons.leccion",
                        verbose_name="Lección",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metricas_ml",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Métrica ML",
                "verbose_name_plural": "Métricas ML",
                "ordering": ["usuario", "leccion__orden"],
                "unique_together": {("usuario", "leccion")},
            },
        ),
        migrations.CreateModel(
            name="RespuestaEscala",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_escala",
                    models.CharField(
                        choices=[
                            ("AUTOEFICACIA_PRE", "Autoeficacia Pre-test"),
                            ("AUTOEFICACIA_POST", "Autoeficacia Post-test"),
                            ("DIAGNOSTICO", "Examen Diagnóstico"),
                            ("FINAL", "Examen Final"),
                        ],
                        max_length=30,
                        verbose_name="Tipo de Escala",
                    ),
                ),
                (
                    "pregunta_numero",
                    models.IntegerField(
                        help_text="Número de la pregunta dentro de la escala/examen",
                        verbose_name="Número de Pregunta",
                    ),
                ),
                (
                    "respuesta",
                    models.IntegerField(
                        help_text="Para autoeficacia: 1-4 (Likert). Para exámenes: 0 (incorrecta) o 1 (correcta)",
                        verbose_name="Respuesta",
                    ),
                ),
                (
                    "fecha_respuesta",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Respuesta"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respuestas_escalas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Respuesta de Escala",
                "verbose_name_plural": "Respuestas de Escalas",
                "ordering": ["usuario", "tipo_escala", "pregunta_numero"],
                "unique_together": {("usuario", "tipo_escala", "pregunta_numero")},
            },
        ),
    ]
