# Generated by Django 5.2.8 on 2025-12-28 00:19

from django.db import migrations


def create_initial_codes(apps, schema_editor):
    """
    Crea los códigos de acceso iniciales para MateLog-AE:
    - LMB para grupo Control
    - MLZ para grupo Experimental
    """
    CodigoAcceso = apps.get_model('ml_adaptive', 'CodigoAcceso')

    CodigoAcceso.objects.get_or_create(
        codigo='LMB',
        defaults={
            'grupo': 'CONTROL',
            'activo': True,
            'descripcion': 'Código de acceso para el grupo de Control. Los estudiantes con este código siguen el flujo tradicional sin adaptación.'
        }
    )

    CodigoAcceso.objects.get_or_create(
        codigo='MLZ',
        defaults={
            'grupo': 'EXPERIMENTAL',
            'activo': True,
            'descripcion': 'Código de acceso para el grupo Experimental. Los estudiantes con este código reciben contenido adaptativo basado en su nivel de autoeficacia.'
        }
    )


def reverse_codes(apps, schema_editor):
    """Elimina los códigos de acceso iniciales si se revierte la migración."""
    CodigoAcceso = apps.get_model('ml_adaptive', 'CodigoAcceso')
    CodigoAcceso.objects.filter(codigo__in=['LMB', 'MLZ']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("ml_adaptive", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_initial_codes, reverse_codes),
    ]
