# Generated by Django 5.2.8 on 2025-12-28 06:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ml_adaptive", "0002_add_initial_access_codes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RespuestaExamenAbierta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_examen",
                    models.CharField(
                        choices=[
                            ("DIAGNOSTICO", "Examen Diagnóstico"),
                            ("FINAL", "Examen Final"),
                        ],
                        default="FINAL",
                        max_length=20,
                        verbose_name="Tipo de Examen",
                    ),
                ),
                (
                    "pregunta_numero",
                    models.IntegerField(verbose_name="Número de Pregunta"),
                ),
                (
                    "pregunta_texto",
                    models.TextField(
                        help_text="Se guarda para referencia",
                        verbose_name="Texto de la Pregunta",
                    ),
                ),
                (
                    "respuesta_esperada",
                    models.TextField(
                        help_text="Respuesta correcta o esperada para comparación",
                        verbose_name="Respuesta Esperada",
                    ),
                ),
                (
                    "respuesta_estudiante",
                    models.TextField(verbose_name="Respuesta del Estudiante"),
                ),
                (
                    "similitud_automatica",
                    models.FloatField(
                        blank=True,
                        help_text="Porcentaje de similitud calculado automáticamente",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                        verbose_name="Similitud Automática (%)",
                    ),
                ),
                (
                    "aprobada_automatica",
                    models.BooleanField(
                        blank=True,
                        help_text="True si similitud >= 70%",
                        null=True,
                        verbose_name="Aprobada Automáticamente",
                    ),
                ),
                (
                    "estado_revision",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente de Revisión"),
                            ("APROBADA", "Aprobada"),
                            ("RECHAZADA", "Rechazada"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                        verbose_name="Estado de Revisión",
                    ),
                ),
                (
                    "aprobada_manual",
                    models.BooleanField(
                        blank=True,
                        help_text="Decisión final del administrador",
                        null=True,
                        verbose_name="Aprobada Manualmente",
                    ),
                ),
                (
                    "feedback_admin",
                    models.TextField(
                        blank=True,
                        help_text="Comentarios del revisor",
                        verbose_name="Feedback del Administrador",
                    ),
                ),
                (
                    "fecha_revision",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Revisión"
                    ),
                ),
                (
                    "fecha_respuesta",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Respuesta"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Modificación"
                    ),
                ),
                (
                    "revisado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revisiones_realizadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Revisado Por",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respuestas_abiertas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Respuesta Abierta de Examen",
                "verbose_name_plural": "Respuestas Abiertas de Exámenes",
                "ordering": ["usuario", "tipo_examen", "pregunta_numero"],
                "unique_together": {("usuario", "tipo_examen", "pregunta_numero")},
            },
        ),
    ]
